version: '3'
services:
  java-app-docker:
    image: 139.59.141.141:8082/java-app-docker:1.1
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
    ports:
    - 8080:8080
    container_name: java-app-docker
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
    
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8083:80
    environment:
      - PMA_HOSTS=mysql
    container_name: phpmyadmin
volumes:
  mysql-data:
    driver: local